// Mocks generated by Mockito 5.4.6 from annotations
// in zebrautil/test/zebra_component_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter/services.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:zebrautil/models/communication_policy_options.dart' as _i12;
import 'package:zebrautil/models/print_enums.dart' as _i10;
import 'package:zebrautil/models/print_operation_tracker.dart' as _i9;
import 'package:zebrautil/models/print_options.dart' as _i13;
import 'package:zebrautil/models/result.dart' as _i3;
import 'package:zebrautil/models/zebra_device.dart' as _i8;
import 'package:zebrautil/zebra_printer.dart' as _i2;
import 'package:zebrautil/zebra_printer_discovery.dart' as _i4;
import 'package:zebrautil/zebrautil.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeZebraController_0 extends _i1.SmartFake
    implements _i2.ZebraController {
  _FakeZebraController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResult_1<T> extends _i1.SmartFake implements _i3.Result<T> {
  _FakeResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeZebraPrinter_2 extends _i1.SmartFake implements _i2.ZebraPrinter {
  _FakeZebraPrinter_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeZebraPrinterDiscovery_3 extends _i1.SmartFake
    implements _i4.ZebraPrinterDiscovery {
  _FakeZebraPrinterDiscovery_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePrintState_4 extends _i1.SmartFake implements _i5.PrintState {
  _FakePrintState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ZebraPrinter].
///
/// See the documentation for Mockito's code generation for more information.
class MockZebraPrinter extends _i1.Mock implements _i2.ZebraPrinter {
  MockZebraPrinter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get instanceId => (super.noSuchMethod(
        Invocation.getter(#instanceId),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#instanceId),
        ),
      ) as String);

  @override
  _i2.ZebraController get controller => (super.noSuchMethod(
        Invocation.getter(#controller),
        returnValue: _FakeZebraController_0(
          this,
          Invocation.getter(#controller),
        ),
      ) as _i2.ZebraController);

  @override
  bool get isRotated => (super.noSuchMethod(
        Invocation.getter(#isRotated),
        returnValue: false,
      ) as bool);

  @override
  bool get isScanning => (super.noSuchMethod(
        Invocation.getter(#isScanning),
        returnValue: false,
      ) as bool);

  @override
  bool get shouldSync => (super.noSuchMethod(
        Invocation.getter(#shouldSync),
        returnValue: false,
      ) as bool);

  @override
  set isRotated(bool? _isRotated) => super.noSuchMethod(
        Invocation.setter(
          #isRotated,
          _isRotated,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isScanning(bool? _isScanning) => super.noSuchMethod(
        Invocation.setter(
          #isScanning,
          _isScanning,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set shouldSync(bool? _shouldSync) => super.noSuchMethod(
        Invocation.setter(
          #shouldSync,
          _shouldSync,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Stream<_i8.ZebraDevice> discoverBTClassicStream({int? timeout = 5000}) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverBTClassicStream,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i7.Stream<_i8.ZebraDevice>.empty(),
      ) as _i7.Stream<_i8.ZebraDevice>);

  @override
  _i7.Stream<_i8.ZebraDevice> discoverLocalBroadcastStream(
          {int? timeout = 5000}) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverLocalBroadcastStream,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i7.Stream<_i8.ZebraDevice>.empty(),
      ) as _i7.Stream<_i8.ZebraDevice>);

  @override
  _i7.Stream<_i8.ZebraDevice> discoverSubnetStream({
    String? subnet = '192.168.1',
    int? timeout = 5000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverSubnetStream,
          [],
          {
            #subnet: subnet,
            #timeout: timeout,
          },
        ),
        returnValue: _i7.Stream<_i8.ZebraDevice>.empty(),
      ) as _i7.Stream<_i8.ZebraDevice>);

  @override
  _i7.Stream<_i8.ZebraDevice> discoverDirectedBroadcastStream({
    String? ipAddress = '192.168.1.255',
    int? timeout = 5000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverDirectedBroadcastStream,
          [],
          {
            #ipAddress: ipAddress,
            #timeout: timeout,
          },
        ),
        returnValue: _i7.Stream<_i8.ZebraDevice>.empty(),
      ) as _i7.Stream<_i8.ZebraDevice>);

  @override
  _i7.Stream<_i8.ZebraDevice> discoverMulticastStream({
    int? hops = 5,
    int? timeout = 5000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverMulticastStream,
          [],
          {
            #hops: hops,
            #timeout: timeout,
          },
        ),
        returnValue: _i7.Stream<_i8.ZebraDevice>.empty(),
      ) as _i7.Stream<_i8.ZebraDevice>);

  @override
  _i7.Stream<_i8.ZebraDevice> discoverBTClassic({int? timeout = 5000}) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverBTClassic,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i7.Stream<_i8.ZebraDevice>.empty(),
      ) as _i7.Stream<_i8.ZebraDevice>);

  @override
  _i7.Stream<_i8.ZebraDevice> discoverLocalBroadcast({int? timeout = 5000}) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverLocalBroadcast,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i7.Stream<_i8.ZebraDevice>.empty(),
      ) as _i7.Stream<_i8.ZebraDevice>);

  @override
  _i7.Stream<_i8.ZebraDevice> discoverSubnet({
    String? subnet = '192.168.1',
    int? timeout = 5000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverSubnet,
          [],
          {
            #subnet: subnet,
            #timeout: timeout,
          },
        ),
        returnValue: _i7.Stream<_i8.ZebraDevice>.empty(),
      ) as _i7.Stream<_i8.ZebraDevice>);

  @override
  _i7.Stream<_i8.ZebraDevice> discoverDirectedBroadcast({
    String? ipAddress = '192.168.1.255',
    int? timeout = 5000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverDirectedBroadcast,
          [],
          {
            #ipAddress: ipAddress,
            #timeout: timeout,
          },
        ),
        returnValue: _i7.Stream<_i8.ZebraDevice>.empty(),
      ) as _i7.Stream<_i8.ZebraDevice>);

  @override
  _i7.Stream<_i8.ZebraDevice> discoverMulticast({
    int? hops = 5,
    int? timeout = 5000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverMulticast,
          [],
          {
            #hops: hops,
            #timeout: timeout,
          },
        ),
        returnValue: _i7.Stream<_i8.ZebraDevice>.empty(),
      ) as _i7.Stream<_i8.ZebraDevice>);

  @override
  _i7.Future<_i3.Result<void>> stopDiscovery() => (super.noSuchMethod(
        Invocation.method(
          #stopDiscovery,
          [],
        ),
        returnValue: _i7.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #stopDiscovery,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Result<void>>);

  @override
  _i7.Future<_i3.Result<void>> connectToPrinter(String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectToPrinter,
          [address],
        ),
        returnValue: _i7.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #connectToPrinter,
            [address],
          ),
        )),
      ) as _i7.Future<_i3.Result<void>>);

  @override
  _i7.Future<_i3.Result<void>> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i7.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #disconnect,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Result<void>>);

  @override
  _i7.Future<_i3.Result<_i9.PrintOperationTracker>> print({
    required String? data,
    _i10.PrintFormat? format = _i10.PrintFormat.zpl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #print,
          [],
          {
            #data: data,
            #format: format,
          },
        ),
        returnValue: _i7.Future<_i3.Result<_i9.PrintOperationTracker>>.value(
            _FakeResult_1<_i9.PrintOperationTracker>(
          this,
          Invocation.method(
            #print,
            [],
            {
              #data: data,
              #format: format,
            },
          ),
        )),
      ) as _i7.Future<_i3.Result<_i9.PrintOperationTracker>>);

  @override
  _i7.Future<_i3.Result<Map<String, dynamic>>> getPrinterStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrinterStatus,
          [],
        ),
        returnValue: _i7.Future<_i3.Result<Map<String, dynamic>>>.value(
            _FakeResult_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getPrinterStatus,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Result<Map<String, dynamic>>>);

  @override
  _i7.Future<_i3.Result<Map<String, dynamic>>> getDetailedPrinterStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailedPrinterStatus,
          [],
        ),
        returnValue: _i7.Future<_i3.Result<Map<String, dynamic>>>.value(
            _FakeResult_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getDetailedPrinterStatus,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Result<Map<String, dynamic>>>);

  @override
  _i7.Future<_i3.Result<String?>> getSetting(String? setting) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSetting,
          [setting],
        ),
        returnValue:
            _i7.Future<_i3.Result<String?>>.value(_FakeResult_1<String?>(
          this,
          Invocation.method(
            #getSetting,
            [setting],
          ),
        )),
      ) as _i7.Future<_i3.Result<String?>>);

  @override
  void rotate() => super.noSuchMethod(
        Invocation.method(
          #rotate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i3.Result<bool>> isPrinterConnected() => (super.noSuchMethod(
        Invocation.method(
          #isPrinterConnected,
          [],
        ),
        returnValue: _i7.Future<_i3.Result<bool>>.value(_FakeResult_1<bool>(
          this,
          Invocation.method(
            #isPrinterConnected,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Result<bool>>);

  @override
  _i7.Future<_i3.Result<String>> getInstanceId() => (super.noSuchMethod(
        Invocation.method(
          #getInstanceId,
          [],
        ),
        returnValue: _i7.Future<_i3.Result<String>>.value(_FakeResult_1<String>(
          this,
          Invocation.method(
            #getInstanceId,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Result<String>>);

  @override
  _i7.Future<void> nativeMethodCallHandler(_i11.MethodCall? methodCall) =>
      (super.noSuchMethod(
        Invocation.method(
          #nativeMethodCallHandler,
          [methodCall],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ZebraPrinterManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockZebraPrinterManager extends _i1.Mock
    implements _i5.ZebraPrinterManager {
  MockZebraPrinterManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ZebraPrinter get printer => (super.noSuchMethod(
        Invocation.getter(#printer),
        returnValue: _FakeZebraPrinter_2(
          this,
          Invocation.getter(#printer),
        ),
      ) as _i2.ZebraPrinter);

  @override
  _i7.Stream<_i8.ZebraDevice?> get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _i7.Stream<_i8.ZebraDevice?>.empty(),
      ) as _i7.Stream<_i8.ZebraDevice?>);

  @override
  _i7.Stream<String> get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i7.Stream<String>.empty(),
      ) as _i7.Stream<String>);

  @override
  _i4.ZebraPrinterDiscovery get discovery => (super.noSuchMethod(
        Invocation.getter(#discovery),
        returnValue: _FakeZebraPrinterDiscovery_3(
          this,
          Invocation.getter(#discovery),
        ),
      ) as _i4.ZebraPrinterDiscovery);

  @override
  List<_i8.ZebraDevice> get discoveredPrinters => (super.noSuchMethod(
        Invocation.getter(#discoveredPrinters),
        returnValue: <_i8.ZebraDevice>[],
      ) as List<_i8.ZebraDevice>);

  @override
  _i7.Future<_i3.Result<bool>> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i7.Future<_i3.Result<bool>>.value(_FakeResult_1<bool>(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Result<bool>>);

  @override
  _i7.Future<_i3.Result<void>> connect(
    dynamic printerIdentifier, {
    _i12.CommunicationPolicyOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [printerIdentifier],
          {#options: options},
        ),
        returnValue: _i7.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #connect,
            [printerIdentifier],
            {#options: options},
          ),
        )),
      ) as _i7.Future<_i3.Result<void>>);

  @override
  _i7.Future<_i3.Result<void>> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i7.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #disconnect,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Result<void>>);

  @override
  _i7.Future<_i3.Result<_i9.PrintOperationTracker>> print(
    String? data, {
    _i13.PrintOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #print,
          [data],
          {#options: options},
        ),
        returnValue: _i7.Future<_i3.Result<_i9.PrintOperationTracker>>.value(
            _FakeResult_1<_i9.PrintOperationTracker>(
          this,
          Invocation.method(
            #print,
            [data],
            {#options: options},
          ),
        )),
      ) as _i7.Future<_i3.Result<_i9.PrintOperationTracker>>);

  @override
  _i7.Future<_i3.Result<Map<String, dynamic>>> getPrinterStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrinterStatus,
          [],
        ),
        returnValue: _i7.Future<_i3.Result<Map<String, dynamic>>>.value(
            _FakeResult_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getPrinterStatus,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Result<Map<String, dynamic>>>);

  @override
  _i7.Future<_i3.Result<Map<String, dynamic>>> getDetailedPrinterStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailedPrinterStatus,
          [],
        ),
        returnValue: _i7.Future<_i3.Result<Map<String, dynamic>>>.value(
            _FakeResult_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getDetailedPrinterStatus,
            [],
          ),
        )),
      ) as _i7.Future<_i3.Result<Map<String, dynamic>>>);

  @override
  _i7.Future<bool> isConnected() => (super.noSuchMethod(
        Invocation.method(
          #isConnected,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  void rotate() => super.noSuchMethod(
        Invocation.method(
          #rotate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SmartPrintManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSmartPrintManager extends _i1.Mock implements _i5.SmartPrintManager {
  MockSmartPrintManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.PrintState get currentState => (super.noSuchMethod(
        Invocation.getter(#currentState),
        returnValue: _FakePrintState_4(
          this,
          Invocation.getter(#currentState),
        ),
      ) as _i5.PrintState);

  @override
  _i7.Stream<_i5.PrintEvent> get eventStream => (super.noSuchMethod(
        Invocation.getter(#eventStream),
        returnValue: _i7.Stream<_i5.PrintEvent>.empty(),
      ) as _i7.Stream<_i5.PrintEvent>);

  @override
  bool get isCancelled => (super.noSuchMethod(
        Invocation.getter(#isCancelled),
        returnValue: false,
      ) as bool);

  @override
  bool get canCancel => (super.noSuchMethod(
        Invocation.getter(#canCancel),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> smartPrint({
    required String? data,
    _i8.ZebraDevice? device,
    int? maxAttempts = 3,
    _i13.PrintOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #smartPrint,
          [],
          {
            #data: data,
            #device: device,
            #maxAttempts: maxAttempts,
            #options: options,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void cancel() => super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  double getProgress() => (super.noSuchMethod(
        Invocation.method(
          #getProgress,
          [],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  String getCurrentStepDescription() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentStepDescription,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getCurrentStepDescription,
            [],
          ),
        ),
      ) as String);

  @override
  bool forceCancel() => (super.noSuchMethod(
        Invocation.method(
          #forceCancel,
          [],
        ),
        returnValue: false,
      ) as bool);
}

/// A class which mocks [ZebraPrinterDiscovery].
///
/// See the documentation for Mockito's code generation for more information.
class MockZebraPrinterDiscovery extends _i1.Mock
    implements _i4.ZebraPrinterDiscovery {
  MockZebraPrinterDiscovery() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isScanning => (super.noSuchMethod(
        Invocation.getter(#isScanning),
        returnValue: false,
      ) as bool);

  @override
  _i7.Stream<List<_i8.ZebraDevice>> get devices => (super.noSuchMethod(
        Invocation.getter(#devices),
        returnValue: _i7.Stream<List<_i8.ZebraDevice>>.empty(),
      ) as _i7.Stream<List<_i8.ZebraDevice>>);

  @override
  _i7.Stream<String> get status => (super.noSuchMethod(
        Invocation.getter(#status),
        returnValue: _i7.Stream<String>.empty(),
      ) as _i7.Stream<String>);

  @override
  List<_i8.ZebraDevice> get discoveredPrinters => (super.noSuchMethod(
        Invocation.getter(#discoveredPrinters),
        returnValue: <_i8.ZebraDevice>[],
      ) as List<_i8.ZebraDevice>);

  @override
  _i7.Future<void> initialize({
    _i2.ZebraController? controller,
    dynamic Function(String)? statusCallback,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #controller: controller,
            #statusCallback: statusCallback,
          },
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.Result<List<_i8.ZebraDevice>>> discoverPrinters(
          {Duration? timeout = const Duration(seconds: 10)}) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverPrinters,
          [],
          {#timeout: timeout},
        ),
        returnValue: _i7.Future<_i3.Result<List<_i8.ZebraDevice>>>.value(
            _FakeResult_1<List<_i8.ZebraDevice>>(
          this,
          Invocation.method(
            #discoverPrinters,
            [],
            {#timeout: timeout},
          ),
        )),
      ) as _i7.Future<_i3.Result<List<_i8.ZebraDevice>>>);

  @override
  _i7.Stream<List<_i8.ZebraDevice>> discoverPrintersStream({
    Duration? timeout = const Duration(seconds: 10),
    int? stopAfterCount,
    bool? stopOnFirstPrinter = false,
    bool? includeWifi = true,
    bool? includeBluetooth = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverPrintersStream,
          [],
          {
            #timeout: timeout,
            #stopAfterCount: stopAfterCount,
            #stopOnFirstPrinter: stopOnFirstPrinter,
            #includeWifi: includeWifi,
            #includeBluetooth: includeBluetooth,
          },
        ),
        returnValue: _i7.Stream<List<_i8.ZebraDevice>>.empty(),
      ) as _i7.Stream<List<_i8.ZebraDevice>>);

  @override
  _i7.Future<_i3.Result<List<_i8.ZebraDevice>>> discoverPrintersUntilFirst({
    Duration? timeout = const Duration(seconds: 10),
    bool? includeWifi = true,
    bool? includeBluetooth = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverPrintersUntilFirst,
          [],
          {
            #timeout: timeout,
            #includeWifi: includeWifi,
            #includeBluetooth: includeBluetooth,
          },
        ),
        returnValue: _i7.Future<_i3.Result<List<_i8.ZebraDevice>>>.value(
            _FakeResult_1<List<_i8.ZebraDevice>>(
          this,
          Invocation.method(
            #discoverPrintersUntilFirst,
            [],
            {
              #timeout: timeout,
              #includeWifi: includeWifi,
              #includeBluetooth: includeBluetooth,
            },
          ),
        )),
      ) as _i7.Future<_i3.Result<List<_i8.ZebraDevice>>>);

  @override
  _i7.Future<_i3.Result<List<_i8.ZebraDevice>>> discoverPrintersCount({
    required int? count,
    Duration? timeout = const Duration(seconds: 10),
    bool? includeWifi = true,
    bool? includeBluetooth = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverPrintersCount,
          [],
          {
            #count: count,
            #timeout: timeout,
            #includeWifi: includeWifi,
            #includeBluetooth: includeBluetooth,
          },
        ),
        returnValue: _i7.Future<_i3.Result<List<_i8.ZebraDevice>>>.value(
            _FakeResult_1<List<_i8.ZebraDevice>>(
          this,
          Invocation.method(
            #discoverPrintersCount,
            [],
            {
              #count: count,
              #timeout: timeout,
              #includeWifi: includeWifi,
              #includeBluetooth: includeBluetooth,
            },
          ),
        )),
      ) as _i7.Future<_i3.Result<List<_i8.ZebraDevice>>>);

  @override
  _i7.Future<void> stopDiscovery() => (super.noSuchMethod(
        Invocation.method(
          #stopDiscovery,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.ZebraDevice>> findPairedPrinters() => (super.noSuchMethod(
        Invocation.method(
          #findPairedPrinters,
          [],
        ),
        returnValue:
            _i7.Future<List<_i8.ZebraDevice>>.value(<_i8.ZebraDevice>[]),
      ) as _i7.Future<List<_i8.ZebraDevice>>);

  @override
  _i7.Future<List<_i8.ZebraDevice>> getAvailablePrinters() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailablePrinters,
          [],
        ),
        returnValue:
            _i7.Future<List<_i8.ZebraDevice>>.value(<_i8.ZebraDevice>[]),
      ) as _i7.Future<List<_i8.ZebraDevice>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
