// Mocks generated by Mockito 5.4.6 from annotations
// in zebrautil/test/unit/models/printer_readiness_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/services.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:zebrautil/internal/communication_policy.dart' as _i11;
import 'package:zebrautil/models/communication_policy_options.dart' as _i12;
import 'package:zebrautil/models/connection_event.dart' as _i6;
import 'package:zebrautil/models/print_enums.dart' as _i9;
import 'package:zebrautil/models/print_operation_tracker.dart' as _i8;
import 'package:zebrautil/models/result.dart' as _i3;
import 'package:zebrautil/models/zebra_device.dart' as _i7;
import 'package:zebrautil/zebra_printer.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeZebraController_0 extends _i1.SmartFake
    implements _i2.ZebraController {
  _FakeZebraController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResult_1<T> extends _i1.SmartFake implements _i3.Result<T> {
  _FakeResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ZebraPrinter].
///
/// See the documentation for Mockito's code generation for more information.
class MockZebraPrinter extends _i1.Mock implements _i2.ZebraPrinter {
  MockZebraPrinter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get instanceId => (super.noSuchMethod(
        Invocation.getter(#instanceId),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#instanceId),
        ),
      ) as String);

  @override
  _i2.ZebraController get controller => (super.noSuchMethod(
        Invocation.getter(#controller),
        returnValue: _FakeZebraController_0(
          this,
          Invocation.getter(#controller),
        ),
      ) as _i2.ZebraController);

  @override
  bool get isRotated => (super.noSuchMethod(
        Invocation.getter(#isRotated),
        returnValue: false,
      ) as bool);

  @override
  bool get isScanning => (super.noSuchMethod(
        Invocation.getter(#isScanning),
        returnValue: false,
      ) as bool);

  @override
  bool get shouldSync => (super.noSuchMethod(
        Invocation.getter(#shouldSync),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<_i6.ConnectionEvent> get connectionEvents => (super.noSuchMethod(
        Invocation.getter(#connectionEvents),
        returnValue: _i5.Stream<_i6.ConnectionEvent>.empty(),
      ) as _i5.Stream<_i6.ConnectionEvent>);

  @override
  set isRotated(bool? _isRotated) => super.noSuchMethod(
        Invocation.setter(
          #isRotated,
          _isRotated,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isScanning(bool? _isScanning) => super.noSuchMethod(
        Invocation.setter(
          #isScanning,
          _isScanning,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set shouldSync(bool? _shouldSync) => super.noSuchMethod(
        Invocation.setter(
          #shouldSync,
          _shouldSync,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Stream<_i7.ZebraDevice> discoverBTClassicStream({
    int? timeout = 5000,
    _i2.DiscoveryWarningCallback? onWarning,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverBTClassicStream,
          [],
          {
            #timeout: timeout,
            #onWarning: onWarning,
          },
        ),
        returnValue: _i5.Stream<_i7.ZebraDevice>.empty(),
      ) as _i5.Stream<_i7.ZebraDevice>);

  @override
  _i5.Stream<_i7.ZebraDevice> discoverLocalBroadcastStream({
    int? timeout = 5000,
    _i2.DiscoveryWarningCallback? onWarning,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverLocalBroadcastStream,
          [],
          {
            #timeout: timeout,
            #onWarning: onWarning,
          },
        ),
        returnValue: _i5.Stream<_i7.ZebraDevice>.empty(),
      ) as _i5.Stream<_i7.ZebraDevice>);

  @override
  _i5.Stream<_i7.ZebraDevice> discoverSubnetStream({
    String? subnet = '192.168.1',
    int? timeout = 5000,
    _i2.DiscoveryWarningCallback? onWarning,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverSubnetStream,
          [],
          {
            #subnet: subnet,
            #timeout: timeout,
            #onWarning: onWarning,
          },
        ),
        returnValue: _i5.Stream<_i7.ZebraDevice>.empty(),
      ) as _i5.Stream<_i7.ZebraDevice>);

  @override
  _i5.Stream<_i7.ZebraDevice> discoverDirectedBroadcastStream({
    String? ipAddress = '192.168.1.255',
    int? timeout = 5000,
    _i2.DiscoveryWarningCallback? onWarning,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverDirectedBroadcastStream,
          [],
          {
            #ipAddress: ipAddress,
            #timeout: timeout,
            #onWarning: onWarning,
          },
        ),
        returnValue: _i5.Stream<_i7.ZebraDevice>.empty(),
      ) as _i5.Stream<_i7.ZebraDevice>);

  @override
  _i5.Stream<_i7.ZebraDevice> discoverMulticastStream({
    int? hops = 5,
    int? timeout = 5000,
    _i2.DiscoveryWarningCallback? onWarning,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverMulticastStream,
          [],
          {
            #hops: hops,
            #timeout: timeout,
            #onWarning: onWarning,
          },
        ),
        returnValue: _i5.Stream<_i7.ZebraDevice>.empty(),
      ) as _i5.Stream<_i7.ZebraDevice>);

  @override
  _i5.Stream<_i7.ZebraDevice> discoverBTClassic({
    int? timeout = 5000,
    _i2.DiscoveryWarningCallback? onWarning,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverBTClassic,
          [],
          {
            #timeout: timeout,
            #onWarning: onWarning,
          },
        ),
        returnValue: _i5.Stream<_i7.ZebraDevice>.empty(),
      ) as _i5.Stream<_i7.ZebraDevice>);

  @override
  _i5.Stream<_i7.ZebraDevice> discoverLocalBroadcast({
    int? timeout = 5000,
    _i2.DiscoveryWarningCallback? onWarning,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverLocalBroadcast,
          [],
          {
            #timeout: timeout,
            #onWarning: onWarning,
          },
        ),
        returnValue: _i5.Stream<_i7.ZebraDevice>.empty(),
      ) as _i5.Stream<_i7.ZebraDevice>);

  @override
  _i5.Stream<_i7.ZebraDevice> discoverSubnet({
    String? subnet = '192.168.1',
    int? timeout = 5000,
    _i2.DiscoveryWarningCallback? onWarning,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverSubnet,
          [],
          {
            #subnet: subnet,
            #timeout: timeout,
            #onWarning: onWarning,
          },
        ),
        returnValue: _i5.Stream<_i7.ZebraDevice>.empty(),
      ) as _i5.Stream<_i7.ZebraDevice>);

  @override
  _i5.Stream<_i7.ZebraDevice> discoverDirectedBroadcast({
    String? ipAddress = '192.168.1.255',
    int? timeout = 5000,
    _i2.DiscoveryWarningCallback? onWarning,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverDirectedBroadcast,
          [],
          {
            #ipAddress: ipAddress,
            #timeout: timeout,
            #onWarning: onWarning,
          },
        ),
        returnValue: _i5.Stream<_i7.ZebraDevice>.empty(),
      ) as _i5.Stream<_i7.ZebraDevice>);

  @override
  _i5.Stream<_i7.ZebraDevice> discoverMulticast({
    int? hops = 5,
    int? timeout = 5000,
    _i2.DiscoveryWarningCallback? onWarning,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discoverMulticast,
          [],
          {
            #hops: hops,
            #timeout: timeout,
            #onWarning: onWarning,
          },
        ),
        returnValue: _i5.Stream<_i7.ZebraDevice>.empty(),
      ) as _i5.Stream<_i7.ZebraDevice>);

  @override
  _i5.Future<_i3.Result<void>> stopDiscovery() => (super.noSuchMethod(
        Invocation.method(
          #stopDiscovery,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #stopDiscovery,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<void>> connectToPrinter(String? address) =>
      (super.noSuchMethod(
        Invocation.method(
          #connectToPrinter,
          [address],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #connectToPrinter,
            [address],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<void>> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #disconnect,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<_i8.PrintOperationTracker>> print({
    required String? data,
    _i9.PrintFormat? format = _i9.PrintFormat.zpl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #print,
          [],
          {
            #data: data,
            #format: format,
          },
        ),
        returnValue: _i5.Future<_i3.Result<_i8.PrintOperationTracker>>.value(
            _FakeResult_1<_i8.PrintOperationTracker>(
          this,
          Invocation.method(
            #print,
            [],
            {
              #data: data,
              #format: format,
            },
          ),
        )),
      ) as _i5.Future<_i3.Result<_i8.PrintOperationTracker>>);

  @override
  _i5.Future<_i3.Result<Map<String, dynamic>>> getPrinterStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrinterStatus,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<Map<String, dynamic>>>.value(
            _FakeResult_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getPrinterStatus,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<Map<String, dynamic>>>);

  @override
  _i5.Future<_i3.Result<Map<String, dynamic>>> getDetailedPrinterStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetailedPrinterStatus,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<Map<String, dynamic>>>.value(
            _FakeResult_1<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getDetailedPrinterStatus,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<Map<String, dynamic>>>);

  @override
  _i5.Future<_i3.Result<String?>> getSetting(String? setting) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSetting,
          [setting],
        ),
        returnValue:
            _i5.Future<_i3.Result<String?>>.value(_FakeResult_1<String?>(
          this,
          Invocation.method(
            #getSetting,
            [setting],
          ),
        )),
      ) as _i5.Future<_i3.Result<String?>>);

  @override
  void rotate() => super.noSuchMethod(
        Invocation.method(
          #rotate,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i3.Result<bool>> isPrinterConnected({bool? forceCheck = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #isPrinterConnected,
          [],
          {#forceCheck: forceCheck},
        ),
        returnValue: _i5.Future<_i3.Result<bool>>.value(_FakeResult_1<bool>(
          this,
          Invocation.method(
            #isPrinterConnected,
            [],
            {#forceCheck: forceCheck},
          ),
        )),
      ) as _i5.Future<_i3.Result<bool>>);

  @override
  _i5.Future<_i3.Result<void>> sendCommand(String? command) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendCommand,
          [command],
        ),
        returnValue: _i5.Future<_i3.Result<void>>.value(_FakeResult_1<void>(
          this,
          Invocation.method(
            #sendCommand,
            [command],
          ),
        )),
      ) as _i5.Future<_i3.Result<void>>);

  @override
  _i5.Future<_i3.Result<String>> getInstanceId() => (super.noSuchMethod(
        Invocation.method(
          #getInstanceId,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<String>>.value(_FakeResult_1<String>(
          this,
          Invocation.method(
            #getInstanceId,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<String>>);

  @override
  _i5.Future<void> nativeMethodCallHandler(_i10.MethodCall? methodCall) =>
      (super.noSuchMethod(
        Invocation.method(
          #nativeMethodCallHandler,
          [methodCall],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CommunicationPolicy].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommunicationPolicy extends _i1.Mock
    implements _i11.CommunicationPolicy {
  MockCommunicationPolicy() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Result<T>> execute<T>(
    _i5.Future<_i3.Result<T>> Function()? operation,
    String? operationName, {
    _i12.CommunicationPolicyOptions? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [
            operation,
            operationName,
          ],
          {#options: options},
        ),
        returnValue: _i5.Future<_i3.Result<T>>.value(_FakeResult_1<T>(
          this,
          Invocation.method(
            #execute,
            [
              operation,
              operationName,
            ],
            {#options: options},
          ),
        )),
      ) as _i5.Future<_i3.Result<T>>);

  @override
  _i5.Future<_i3.Result<bool>> getPrinterConnectionStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrinterConnectionStatus,
          [],
        ),
        returnValue: _i5.Future<_i3.Result<bool>>.value(_FakeResult_1<bool>(
          this,
          Invocation.method(
            #getPrinterConnectionStatus,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Result<bool>>);

  @override
  void forceConnectionCheck() => super.noSuchMethod(
        Invocation.method(
          #forceConnectionCheck,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getPolicyStats() => (super.noSuchMethod(
        Invocation.method(
          #getPolicyStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
