name: zebrautil
description: "A flutter plugin for working with zebra printers"
version: 2.1.1
homepage: https://github.com/shashwatxx/zebrautil
repository: https://github.com/anthonyR012/zebra_printer_utility

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  plugin:
    platforms:
      android:
        package: com.rubdev.zebrautil
        pluginClass: ZebraUtilPlugin
      ios:
        pluginClass: ZebraUtilPlugin
