name: zebrautil
description: A Flutter plugin for discovering and printing to Zebra printers via Bluetooth and network. Supports both ZPL and CPCL languages with auto-correction and retry capabilities.
version: 2.0.28
homepage: https://github.com/bensonarafat/zebrautil
repository: https://github.com/anthonyR012/zebra_printer_utility

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  plugin:
    platforms:
      android:
        package: com.rubdev.zebrautil
        pluginClass: ZebraUtilPlugin
      ios:
        pluginClass: ZebraUtilPlugin
