name: zebrautil
description: A Flutter plugin for discovering and printing to Zebra printers via Bluetooth and network. Supports both ZPL and CPCL languages with auto-correction and retry capabilities.
version: 2.0.38
homepage: https://github.com/jalmeida-at-vonigo/zebra_printer_utility
repository: https://github.com/jalmeida-at-vonigo/zebra_printer_utility

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  mockito: ^5.4.4
  build_runner: ^2.4.11



flutter:
  plugin:
    platforms:
      android:
        package: com.rubdev.zebrautil
        pluginClass: ZebraUtilPlugin
      ios:
        pluginClass: ZebraUtilPlugin
