name: zebrautil
description: A plugin for working with zebra printers and labels, you can find Zebra BLE, WIFI Printers, and print ZPL code to them.
version: 2.0.40
homepage: "https://github.com/anthonyR012/zebra_printer_utility/tree/main"

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  mockito: ^5.4.4
  build_runner: ^2.4.11



flutter:
  plugin:
    platforms:
      android:
        package: com.rubdev.zebrautil
        pluginClass: ZebraUtilPlugin
      ios:
        pluginClass: ZebraUtilPlugin
